"""A minimal MCP server exposing a `query_warehouse` tool backed by the
seeded `warehouse.duckdb` (see ../warehouse/seed.py -- DuckDB's own TPC-H
generator, a real multi-table schema), so `honest-agent run` has something
real -- actual data, actual joins, actual SQL -- to connect to without
needing a company MCP endpoint.

Run standalone with: python mcp_server/server.py (stdio transport).
Point honest-agent at it with:
  honest-agent run --mcp-command "python mcp_server/server.py" ...

Uses the `mcp` package, which comes with honest-agent (Python >=3.10).
"""

from __future__ import annotations

from pathlib import Path

import duckdb
from mcp.server.mcpserver import MCPServer

WAREHOUSE_PATH = Path(__file__).parent.parent / "warehouse.duckdb"
MAX_ROWS = 200  # a naive `select *` on lineitem is 60k+ rows -- cap it rather than dump that into the agent's context

server = MCPServer("agent_quiz_demo")


@server.tool()
def query_warehouse(sql: str) -> str:
    """Run a read-only SQL query against the warehouse (standard TPC-H
    schema, generated by DuckDB's dbgen) and return the result rows.

    Raw tables: orders, lineitem, customer, part, partsupp, supplier,
    nation, region -- see the standard TPC-H schema for their columns
    (orders.o_orderdate, lineitem.l_extendedprice/l_discount/l_orderkey,
    etc.). orders and lineitem join on orders.o_orderkey = lineitem.l_orderkey.

    Derived table: fct_revenue_by_year(year, revenue) -- annual revenue,
    pre-aggregated as sum(l_extendedprice * (1 - l_discount)) per order
    year. Prefer this for revenue questions rather than joining
    orders+lineitem and recomputing that formula by hand.

    Results are capped at 200 rows -- aggregate in SQL rather than pulling
    raw rows and summarizing yourself.
    """
    if not WAREHOUSE_PATH.exists():
        return "error: warehouse.duckdb not found -- run `uv run python warehouse/seed.py` first."
    con = duckdb.connect(str(WAREHOUSE_PATH), read_only=True)
    try:
        rows = con.execute(sql).fetchall()
        columns = [d[0] for d in con.description]
    except Exception as exc:  # noqa: BLE001 -- surfaced back to the agent as the tool result, not raised
        return f"error running query: {exc}"
    finally:
        con.close()

    truncated = len(rows) > MAX_ROWS
    rows = rows[:MAX_ROWS]
    lines = [",".join(columns)] + [",".join(str(v) for v in row) for row in rows]
    if truncated:
        lines.append(f"... truncated to {MAX_ROWS} rows, aggregate in SQL instead of relying on raw rows")
    return "\n".join(lines)


if __name__ == "__main__":
    server.run()
